#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

CKPT_DIR="lingbot-world-base-cam"
IMAGE=""
PROMPT=""
ACTION_PATH=""
ACTION_STRING=""
SIZE="720*1280"
FRAMES="81"
SEED="42"
SAVE_FILE=""
MODE="auto"
SINGBOX_PORT="${SINGBOX_PORT:-}"
HF_ENDPOINT="${HF_ENDPOINT:-https://hf-mirror.com}"

usage() {
  cat <<'EOF'
Usage:
  scripts/run_i2v_720p.sh --image PATH --prompt "text prompt" [options]

Required:
  --image PATH             Starting image for image-to-video.
  --prompt TEXT            Text prompt describing the video.

Common options:
  --ckpt-dir DIR           Model checkpoint directory. Default: lingbot-world-base-cam
  --action-path DIR        Optional control directory containing intrinsics.npy and poses.npy.
  --action-string TEXT     Optional keyboard-style control, e.g. "w-20,none-10,a-20".
  --frames N              Number of output frames. Must be 4n+1. Default: 81.
  --size WxH              720p area choice. Default: 720*1280. For landscape use 1280*720.
  --save-file PATH         Output .mp4 path. Default: generated by the repo.
  --mode auto|fast|full    auto uses fast if ckpt has lingbot_world_fast/. Default: auto.
  --seed N                Random seed. Default: 42.
  --singbox-port PORT      Optional local SOCKS port for Singbox, e.g. 1080 or 7890.

Inputs for camera control:
  action-path/intrinsics.npy  shape [num_frames, 4], values [fx, fy, cx, cy]
  action-path/poses.npy       shape [num_frames, 4, 4], OpenCV camera transforms

Notes:
  Output FPS is fixed by this repo config at 16 FPS.
  Duration in seconds is frames / 16.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ckpt-dir) CKPT_DIR="$2"; shift 2 ;;
    --image) IMAGE="$2"; shift 2 ;;
    --prompt) PROMPT="$2"; shift 2 ;;
    --action-path) ACTION_PATH="$2"; shift 2 ;;
    --action-string) ACTION_STRING="$2"; shift 2 ;;
    --frames) FRAMES="$2"; shift 2 ;;
    --size) SIZE="$2"; shift 2 ;;
    --save-file) SAVE_FILE="$2"; shift 2 ;;
    --mode) MODE="$2"; shift 2 ;;
    --seed) SEED="$2"; shift 2 ;;
    --singbox-port) SINGBOX_PORT="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$IMAGE" || -z "$PROMPT" ]]; then
  usage >&2
  exit 2
fi

if [[ ! -d ".venv" ]]; then
  echo "Missing .venv. Run project setup first." >&2
  exit 1
fi

if [[ ! -f "$IMAGE" ]]; then
  echo "Image not found: $IMAGE" >&2
  exit 1
fi

if [[ ! -d "$CKPT_DIR" ]]; then
  echo "Checkpoint directory not found: $CKPT_DIR" >&2
  echo "Download example:"
  echo "  HF_ENDPOINT=https://hf-mirror.com uv run huggingface-cli download robbyant/lingbot-world-base-cam --local-dir ./lingbot-world-base-cam"
  exit 1
fi

if [[ -n "$ACTION_STRING" && -z "$ACTION_PATH" ]]; then
  echo "--action-string requires --action-path because intrinsics.npy is read from that directory." >&2
  exit 1
fi

if [[ -n "$ACTION_PATH" ]]; then
  if [[ ! -f "$ACTION_PATH/intrinsics.npy" ]]; then
    echo "Missing required file: $ACTION_PATH/intrinsics.npy" >&2
    exit 1
  fi
  if [[ -z "$ACTION_STRING" && ! -f "$ACTION_PATH/poses.npy" ]]; then
    echo "Missing required file: $ACTION_PATH/poses.npy" >&2
    exit 1
  fi
fi

case "$MODE" in
  auto|fast|full) ;;
  *) echo "--mode must be one of: auto, fast, full" >&2; exit 2 ;;
esac

source .venv/bin/activate

export HF_ENDPOINT
export TOKENIZERS_PARALLELISM=false

if [[ -n "$SINGBOX_PORT" ]]; then
  export ALL_PROXY="socks5h://127.0.0.1:${SINGBOX_PORT}"
  export HTTP_PROXY="$ALL_PROXY"
  export HTTPS_PROXY="$ALL_PROXY"
  export NO_PROXY="127.0.0.1,localhost"
fi

USE_FAST=0
if [[ "$MODE" == "fast" ]]; then
  USE_FAST=1
elif [[ "$MODE" == "auto" && -d "$CKPT_DIR/lingbot_world_fast" ]]; then
  USE_FAST=1
fi

COMMON_ARGS=(
  --task i2v-A14B
  --size "$SIZE"
  --ckpt_dir "$CKPT_DIR"
  --image "$IMAGE"
  --frame_num "$FRAMES"
  --prompt "$PROMPT"
  --base_seed "$SEED"
  --t5_cpu
  --offload_model true
)

if [[ -n "$ACTION_PATH" ]]; then
  COMMON_ARGS+=(--action_path "$ACTION_PATH")
fi

if [[ -n "$SAVE_FILE" ]]; then
  COMMON_ARGS+=(--save_file "$SAVE_FILE")
fi

echo "Running ${FRAMES} frames at 16 FPS: $(awk "BEGIN { printf \"%.2f\", ${FRAMES}/16 }") seconds of video."
echo "Mode: $([[ "$USE_FAST" == "1" ]] && echo fast || echo full)"

if [[ "$USE_FAST" == "1" ]]; then
  python generate_fast.py "${COMMON_ARGS[@]}"
else
  FULL_ARGS=("${COMMON_ARGS[@]}")
  if [[ -n "$ACTION_STRING" ]]; then
    FULL_ARGS+=(--action_string "$ACTION_STRING" --allow_act2cam)
  fi
  python generate.py "${FULL_ARGS[@]}"
fi
